<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "test_contacts".
 *
 * @property string $id
 * @property string $test_id
 * @property string $phone
 * @property string $email
 *
 * @property \app\models\Test $test
 * @property string $aliasModel
 */
abstract class TestContacts extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'test_contacts';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['test_id'], 'required'],
            [['test_id'], 'integer'],
            [['phone'], 'string', 'max' => 20],
            [['email'], 'string', 'max' => 60],
            [['test_id'], 'exist', 'skipOnError' => true, 'targetClass' => Test::className(), 'targetAttribute' => ['test_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'test_id' => Yii::t('app', 'Test ID'),
            'phone' => Yii::t('app', 'Phone'),
            'email' => Yii::t('app', 'Email'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTest()
    {
        return $this->hasOne(\app\models\Test::className(), ['id' => 'test_id']);
    }


    
    /**
     * @inheritdoc
     * @return testContactsQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\testContactsQuery(get_called_class());
    }


}
